// Generated by CoffeeScript 1.6.2
(function() {
  var Datastore, Rule,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Datastore = (function() {
    function Datastore() {
      this.get = __bind(this.get, this);
      this.set = __bind(this.set, this);      this.constructor._self = this;
      this._object = {};
    }

    Datastore.connect = function() {
      if (Datastore._self) {
        return Datastore._self;
      }
      return new Datastore();
    };

    Datastore.prototype.set = function(key, value) {
      return this._object[key] = value;
    };

    Datastore.prototype.get = function(key) {
      return this._object[key];
    };

    return Datastore;

  }).call(this);

  Rule = (function() {
    Rule.get = function(name) {
      return this.f._rules[name];
    };

    Rule.prototype.clear = function() {
      this._dependencies = void 0;
      this._passes = void 0;
      return this._bound = void 0;
    };

    function Rule(name, _fn) {
      this.name = name;
      this._fn = _fn;
      this.run = __bind(this.run, this);
      this.bind = __bind(this.bind, this);
      this.key = __bind(this.key, this);
      this.passes = __bind(this.passes, this);
      this.dependencies = __bind(this.dependencies, this);
      this._datastore = Datastore.connect();
    }

    Rule.prototype.dependencies = function() {
      var fnStr, keyed, p, params, _i, _len;

      if (this._dependencies == null) {
        fnStr = this._fn.toString();
        params = fnStr.slice(fnStr.indexOf('(') + 1, fnStr.indexOf(')'));
        params = params.match(/([^\s,]+)/g);
        this._dependencies = [];
        this._keys = [];
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          p = params[_i];
          keyed = false;
          if (p[0] === '$') {
            keyed = true;
            p = p.slice(1);
          }
          if (p === 'self') {
            p = this.name;
          }
          p = this.constructor.get(p);
          if (p === void 0) {
            return this._dependencies = [];
          }
          if (keyed) {
            this._keys.push(this._dependencies.length);
          }
          this._dependencies.push(p);
        }
      }
      return this._dependencies;
    };

    Rule.prototype.passes = function(dependencies) {
      var d, dependency, _i, _j, _len, _len1, _ref;

      if (dependencies == null) {
        dependencies = void 0;
      }
      if (!this._passes) {
        this._passes = [];
        _ref = this.dependencies();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          d = _ref[_i];
          this._passes.push(d);
          this._passes.concat(d.passes());
        }
        this._passes.push(this);
      }
      if (dependencies == null) {
        return this._passes;
      }
      if (this._passes.length === 0) {
        return -1;
      }
      for (_j = 0, _len1 = dependencies.length; _j < _len1; _j++) {
        dependency = dependencies[_j];
        if (__indexOf.call(this._passes, dependency) < 0) {
          return -1;
        }
      }
      return this._passes.length;
    };

    Rule.prototype.key = function(args) {
      var i;

      return "" + ([this.name].concat((function() {
        var _i, _len, _ref, _results;

        _ref = this._keys;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _results.push(args[i]);
        }
        return _results;
      }).call(this)).join('_'));
    };

    Rule.prototype.bind = function(rule) {
      var _ref;

      if ((_ref = this._bound) == null) {
        this._bound = [];
      }
      return this._bound.push(rule);
    };

    Rule.prototype.run = function(args) {
      var context, d, dep, i, name, results, x, _i, _j, _len, _len1,
        _this = this;

      results = void 0;
      d = this.dependencies();
      if (args) {
        if (Object.prototype.toString.call(args) === '[object Array]') {
          results = {};
          for (i = _i = 0, _len = d.length; _i < _len; i = ++_i) {
            name = d[i];
            results[name] = args[i];
          }
        } else {
          results = args;
          args = (function() {
            var _j, _len1, _results;

            _results = [];
            for (_j = 0, _len1 = d.length; _j < _len1; _j++) {
              x = d[_j];
              _results.push(args[x.name]);
            }
            return _results;
          })();
        }
      }
      for (i = _j = 0, _len1 = d.length; _j < _len1; i = ++_j) {
        dep = d[i];
        console.log(this.key(args));
        if (dep === this) {
          args[i] = this._datastore.get(this.key(args));
        }
      }
      context = {
        "return": function(val) {
          var results_, rule, _k, _len2, _ref, _ref1, _results;

          results_ = JSON.parse(JSON.stringify(results));
          results_[_this.name] = val;
          _this._datastore.set(_this.key(args), val);
          if ((_ref = _this._bound) == null) {
            _this._bound = [];
          }
          _ref1 = _this._bound;
          _results = [];
          for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
            rule = _ref1[_k];
            _results.push(rule.run(results_));
          }
          return _results;
        }
      };
      return this._fn.apply(context, args);
    };

    return Rule;

  })();

  this.Rule = Rule;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Rule;
  }

}).call(this);
